name = input("Enter your name: ")
usn = input("Enter your USN: ")
course = input("Enter your course: ")
clg =input("enter your college:")

print("\nYour Details:")
print(f"Name: {name}")
print(f"USN: {usn}")
print(f"Course: {course}")
print(f"college:{clg}")
print("H")
